### ISSUE TITLE
Outdated shipped acme-tiny

### ISSUE THREAD

**Issue by chrysn** [qyanu/acme-wrapper#1]
With the bundled acme-tiny, I can't get new certificates any more (raises 403, and raising an exception without the response's payload is somewhat unhelpful behavior on the side of acme-tiny or its HTTP library).

As a workaround, I'm using Debian's shipped acme-tiny, which involves
* setting `acme_tiny=$(command -v acme-tiny)` (resolving is necessary because later the existence is checked; alternatively just neuter the check)
* removing the explicit `python` in front of the invocation (as the program is executable on its own and Python2 is dead for good)

[edit: fat-fingered github's annoying ctrl-return submit before having the post ready; text is done now but I had planned to only submit this once I've tried it all / still WIP]

**Comment by qyanu** [comment]
Oh, somebody is (also) using acme-wrapper besides me. Let's have a look at this issue.

**Comment by qyanu** [comment]
@chrysn so the outdated acme-tiny is updated. but what is this command ``command`` you were mentioning in your workaround?

**Comment by chrysn** [comment]
Thanks!

`command -v` is the POSIX shell built-in equivalent to `which` is [deprecated in debianutils 5.3](https://salsa.debian.org/debian/debianutils/-/blob/master/debian/NEWS).

(Personally, I'm not a big fan of the rampant use of `which` in shell scripts and Makefiles to store the explicit path; PATH does work, and it's easier to ask forgiving in form of a "command not found" than permission.)

**Comment by qyanu** [comment]
new todos on the roadmap:
- which => command
- check if intermediate certs are included twice

(PS: i think using which/command in shell-scripts is better in terms of likelihood of human programming error)
